DEFAULT_PARAMS={
    "Kmeans":{
        "n_clusters":3,
        "init":"k-means++",
        "n_init":"warn",
        "max_iter":300,
        "tol":1e-4,
        "verbose":0,
        "random_state":None,
        "copy_x":True,
        "algorithm":"lloyd"
    },
    "SphericalKmeans":{
        "n_clusters":3,
        "init":"k-means++",
        "n_init":"warn",
        "max_iter":300,
        "tol":1e-4,
        "verbose":0,
        "random_state":None,
        "copy_x":True,
        "algorithm":"lloyd"
    },
    "CAH":{
        "method":"ward",
    }

}